apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-data
  labels:
    component: {{ template "fullname" . }}
    role: data
spec:
  selector:
    component: {{ template "fullname" . }}-data
    role: data
  ports:
  - name: transport
    port: {{ .Values.service.transportPort }}
    targetPort: 9300
    protocol: TCP
