apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  labels:
    component: {{ template "fullname" . }}
    role: client
spec:
  type: {{ .Values.service.type }}
  selector:
    component: {{ template "fullname" . }}
    role: client
  ports:
  - name: http
    port: {{ .Values.service.httpPort }}
    targetPort: 9200
    protocol: TCP
